### ISSUE TITLE
A problem when I was running the example (NREL5MW.ALMAdvancedFAST8)

### ISSUE THREAD

**Issue by nnn741** [NREL/SOWFA#110]
![image](https://github.com/user-attachments/assets/f85349f4-62df-4a2f-8024-71868c0c7a0a)
When I tried to run the example after compiling, I got an error. I am confused. I hope someone can help me.

**Comment by nnn741** [comment]
I successfully compiled openfast2.4 with gcc g++ gfortran-7.5, and successfully compiled open foam-2.4 with gcc g++ gfortran-4.8.5. Then I successfully compiled sowfa with gcc g++ gfortran-4.8.5, but encountered the problem shown in the figure when running. I don't know whether it is a compilation error or my parameters are wrong. This problem has troubled me for many days. I hope someone can help me

**Comment by heyi888** [comment]
It seems to be a parameter setting error. You need to ensure that the FAST time step (dt) multiplied by the total simulation time matches the time range of the wind input file.
