### ISSUE TITLE
indexing typo

### ISSUE THREAD

**Issue by ewquon** [NREL/SOWFA#12]
The cartesian wind vectors are indexed as 
`bladeWindVectorsCartesian[i][i][k]`
instead of
`bladeWindVectorsCartesian[i][j][k]`

This occurs in horizontalAxisWindTurbinesALMfastv8 as well as horizontalAxisWindTurbinesALMOpenFAST. 

https://github.com/NREL/SOWFA/blob/513cab99d8010be2aba677f82a893e31d7a02d23/src/turbineModels/turbineModelsOpenFAST/horizontalAxisWindTurbinesALMOpenFAST/horizontalAxisWindTurbinesALMOpenFAST.C#L2307

**Comment by mchurchf** [comment]
This should all be fixed now.  Sorry about this bug.
