### ISSUE TITLE
dlopen error in libuserincompressibleLESModels.so: undefined symbol: _ZTIN4Foam14incompressible9LESModels11GenEddyViscE

### ISSUE THREAD

**Issue by hcOnel** [NREL/SOWFA#25]
Hello,
I have successfully compiled SOWFA on OpenFOAM-2.4.x and trying to solve the `example.ABL.flatTerrain.stable` example case as a precursor for an ALM simulation. Compilation logs does not include any errors and all libraries are shown as up to date as recommended in the README file.
However, after running `runscript.preprocess`, i get the following warnings and errors at top of each log file (`log.blockMesh`, `log.checkMesh.1`, `log.decomposePar`, `log.renumberMesh`):

```
--> FOAM Warning : 
    From function dlOpen(const fileName&, const bool)
    in file POSIX.C at line 1179
    dlopen error : /home/canon/OpenFOAM/canon-2.4.x/platforms/linux64GccDPOpt/lib/libuserincompressibleLESModels.so: undefined symbol: _ZTIN4Foam14incompressible9LESModels11GenEddyViscE
--> FOAM Warning : 
    From function dlLibraryTable::open(const fileName&, const bool)
    in file db/dynamicLibrary/dlLibraryTable/dlLibraryTable.C at line 99
    could not load "libuserincompressibleLESModels.so"

```
This library seems to be compiled successfully and up to date in wmake log file and I could not figure out the cause of this error. Is this ignorable?

**Comment by Bartdoekemeijer** [comment]
You can safely ignore these warnings.

**Comment by ShenghaiLiao** [comment]
hello ,@hcOnel ,I'm facing the same problem.How did you solve it . I would be appraciate if you can send some help.

**Comment by ewquon** [comment]
This message no longer appears for newer versions of SOWFA in which "libuserfiniteVolume.so" and "libuserincompressibleLESModels.so" have been renamed as "libSOWFAfiniteVolume.so" and "libSOWFAincompressibleLESModels.so". For older versions, as @Bartdoekemeijer has said before, this error may be safely ignored.
