### ISSUE TITLE
buoyantPressure is not supported in the versions above 2.3.0 of OpenFOAM

### ISSUE THREAD

**Issue by ghost** [NREL/SOWFA#3]
In the file SOWFA/tutorials/precursorABL/generic.neutral/0.original/p_rgh, buoyantPressure type is still used for ABLSolver which is not supported in new OpenFOAM versions, 

```
lower
{
    type            buoyantPressure;
    rho             rhok;
}
```

From the disscussion on cfd-online, 
http://www.cfd-online.com/Forums/openfoam-pre-processing/130887-buoyantpressure-boundary-condition.html
fixedFluxPressure type of p_rgh is used instead. It should be used like
    myPatch
    {
        type            fixedFluxPressure;
    }

refer to 
https://github.com/OpenFOAM/OpenFOAM-2.3.x/blob/master/src/finiteVolume/fields/fvPatchFields/derived/fixedFluxPressure/fixedFluxPressureFvPatchScalarField.H

**Comment by mchurchf** [comment]
This is all fixed to use fixedFluxPressure now.  This is reflected in the solvers and the example cases.
