### ISSUE TITLE
How to set the refLoc in the turbulentABLVelocityControlled BC?

### ISSUE THREAD

**Issue by fastlabb** [NREL/SOWFA#32]
In the ''_SOWFA/src/finiteVolume/fields/fvPatchFields/derived/turbulentABLVelocityControlled/turbulentABLVelocityControlledFvPatchField.H_'', here is a variable **refLoc**, how should it be set? Shouldn't **refLoc** be a three-dimensional coordinate? But looking at the comments in the _***.H_ file, it seems that there is only one scalar value.

I really appreciate any help you can provide.

**Comment by ewquon** [comment]
`refLoc` is defined as a vector, so it should be specified as a list of three components in `(x y z)` form on your boundary patch. Hope this helps.
