### ISSUE TITLE
error in running windPlantSolver.ALMAdvanced

### ISSUE THREAD

**Issue by ShenghaiLiao** [NREL/SOWFA#49]
I'm running example cases from SOWFA
I had successfully run windPlantSolver.ALM in  example.ALM.
And now I'm trying to run windPlantSolver.ALMAdvanced in example.ALMAdvanced using exactly the same precursor data from example.ABL.flatTerrain.neutral. 
the preprocess was quite smooth going,but error came out  next 

/*---------------------------------------------------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     | Version:  2.4.0                                 |
|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/

Build  : 2.4.0
Exec   : windPlantSolver.ALMAdvanced -parallel
Date   : May 02 2019
Time   : 17:11:57
Host   : "c27n11"
PID    : 7306
Case   : /fsa/home/hzxy/xinzhiqiang/run1260/ALMAdvanced
nProcs : 36
Slaves : 
35
(
"c27n11.7307"
"c27n11.7308"
"c13n06.17977"
"c13n06.17978"
"c13n06.17979"
"c13n06.17980"
)

Pstream initialized with:
    floatTransfer      : 0
    nProcsSimpleSum    : 0
    commsType          : nonBlocking
    polling iterations : 0
sigFpe : Enabling floating point exception trapping (FOAM_SIGFPE).
fileModificationChecking : Monitoring run-time modified files using timeStampMaster
allowSystemOperations : Allowing user-supplied system call operations

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
Create time

Create mesh for time = 20000

Reading the gravitational acceleration, g...
Reading planetary rotation rate...
Reading the latitude...
Creating and reading potential temperature field, T...
Creating mean temperature field, Tmean...
Creating fluctuating temperature field, Tprime...
Creating and reading modified pressure field, p_rgh...
Creating and reading velocity field, U...
Creating mean velocity field, Umean...
Creating fluctuating velocity field, Uprime...
Creating and calculating velocity flux field, phi...
Reading/calculating face flux field phi

Reading transport properties...
Selecting incompressible transport model Newtonian
Reading the atmospheric boundary layer properties...
Omega [0 0 -1 0 0 0 0] (0 1.74532925199e-33 0)
Creating turbulence model...
Selecting turbulence model type LESModel
Selecting LES turbulence model oneEqEddyABL
Selecting LES delta type smooth
Selecting LES delta type cubeRootVol
oneEqEddyABLCoeffs
{
    ce              0.93;
    ck              0.0673;
    TName           "T";
    kappatName      "kappat";
}

[0] 
[0] 
[0] --> FOAM FATAL IO ERROR: 
[0] keyword velocityDragCorrType is undefined in dictionary "/fsa/home/hzxy/xinzhiqiang/run1260/ALMAdvanced/constant/turbineArrayProperties.turbine0"
[0] 
[0] file: /fsa/home/hzxy/xinzhiqiang/run1260/ALMAdvanced/constant/turbineArrayProperties.turbine0 from line 25 to line 56.
[0] 
[0]     From function dictionary::lookupEntry(const word&, bool, bool) const
[0]     in file db/dictionary/dictionary.C at line 442.
[0] 
FOAM parallel run exiting
[0] 
[1] 
[1] 
[1] --> FOAM FATAL IO ERROR: 
[1] keyword velocityDragCorrType is undefined in dictionary "IOstream.turbine0"
[1] 
[1] file: IOstream.turbine0 from line 0 to line 0.
[1] 
[1]     From function dictionary::lookupEntry(const word&, bool, bool) const
[1]     in file db/dictionary/dictionary.C at line 442.
[1] 
FOAM parallel run exiting
[1] 
.....
[35] 
[35] 
[35] --> FOAM FATAL IO ERROR: 
[35] keyword velocityDragCorrType is undefined in dictionary "IOstream.turbine0"
[35] 
[35] file: IOstream.turbine0 from line 0 to line 0.
[35] 
[35]     From function dictionary::lookupEntry(const word&, bool, bool) const
[35]     in file db/dictionary/dictionary.C at line 442.
[35] 
FOAM parallel run exiting
[35] 
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 2 in communicator MPI_COMM_WORLD 
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.

I cannot find out what I was missing 
(P.S.:I didn't install OpenFAST and didn't compile windPlantSolver.ALMOpenFAST , does is matter? )
Any reply is very grateful.

**Comment by ShenghaiLiao** [comment]
add
   velocityDragCorrType             "Martinez";
to /ALMAdvanced/constant/turbineArrayProperties

**Comment by fengbao8** [comment]
> keyword velocityDragCorrType is undefined in dictionary "IOstream.turbine0"


Hello, I had the same problem, did you solve it?I'm getting the error

> keyword tipRootLossCorr is undefined in dictionary "/public21/home/sc94363/openfoam6/run/8/example.ALM/constant/turbineArrayProperties.turbine0"
> 
> file: /public21/home/sc94363/openfoam6/run/8/example.ALM/constant/turbineArrayProperties.turbine0 from line 39 to line 78.
> 
>     From function Foam::dictionary &Foam::dictionary::subDict(const Foam::word &)
>     in file db/dictionary/dictionary.C at line 718.
> 
> FOAM exiting

**Comment by rthedin** [comment]
Your question is related to SOWFA-6. Please keep issues related to SOWFA (based on OpenFOAM 2.4.x) and SOWFA-6 (based on OpenFOAM 6) to their own repository.

In any case, the error tells you the issue:
```
keyword velocityDragCorrType is undefined in dictionary "IOstream.turbine0"
```
You do not have `velocityDragCorrType` set. The [reply above](https://github.com/NREL/SOWFA/issues/49#issuecomment-503071189) by Sh-Liao is probably an answer to your question.
