### ISSUE TITLE
OpenFOAM-5.x compatibilitiy

### ISSUE THREAD

**Issue by hcOnel** [NREL/SOWFA#58]
Hello,
Are there any efforts going on for making SOWFA compatible with higher versions of OpenFOAM?

**Comment by Bartdoekemeijer** [comment]
FYI: https://github.com/NREL/SOWFA-6

**Comment by hcOnel** [comment]
Oh, I have never noticed that. Thank you!

**Comment by petebachant** [comment]
Any particular reason that work is going in a new repo versus a branch of this one? I realize OpenFOAM does that as well, but it's sort of unconventional and may lead to confusion.
