### ISSUE TITLE
Installing issue with the OpenFoam 1906

### ISSUE THREAD

**Issue by chandukec** [NREL/SOWFA#60]
Hi,
I am having OpenFoam 1906 and trying to install SOWFA with it. But whenever I am trying to ./Allwmake it is giving lot of errors, like:
In file included from dynLagrangianCs/dynLagrangianCs.C:27:0:
dynLagrangianCs/dynLagrangianCs.H:77:25: fatal error: GenEddyVisc.H: No such file or directory

horizontalAxisWindTurbinesALM/horizontalAxisWindTurbinesALM.C: In constructor ‘Foam::turbineModels::horizontalAxisWindTurbinesALM::horizontalAxisWindTurbinesALM(const volVectorField&)’:
horizontalAxisWindTurbinesALM/horizontalAxisWindTurbinesALM.C:236:59: error: call of overloaded ‘append(Foam::ITstream&)’ is ambiguous
         PreCone.append(turbineProperties.lookup("PreCone"));
horizontalAxisWindTurbinesALM/horizontalAxisWindTurbinesALM.C:272:118: error: call of overloaded ‘append(Foam::ITstream&)’ is ambiguous
             SpeedTorqueTable.append(turbineProperties.subDict("GenTorqueControllerParams").lookup("SpeedTorqueTable"));

It seems that it is not compatible with the OpenFoam 1906 ? Or something I am terribly missing?

**Comment by Bartdoekemeijer** [comment]
Hello,

SOWFA is compatible with OpenFOAM 2.x, not with later versions. Please read the [readme](https://github.com/NREL/SOWFA/blob/master/README.SOWFA) file.

**Comment by mchurchf** [comment]
Please take a look at github.com/NREL/SOWFA-6.  Make sure to switch to the `dev` branch.  That is our updated version of SOWFA that is still a work in progress, but it compiles with OpenFOAM-6.  You may have more luck getting it to compile with OpenFOAM v1906, but I know some libraries will not compile without modification.  We ideally would like this newer version of SOWFA to work with the .org and .com versions of OpenFOAM, but so far have not been able to make that work.
