### ISSUE TITLE
need help for using pisoFoamTurbine.ALM

### ISSUE THREAD

**Issue by ShenghaiLiao** [NREL/SOWFA#61]
Hello,I'm trying to use pisoFoamTurbine.ALM,but I cannot find any examples. So I tried to follow the example.ALM,but have some trouble with file system/fvSchemes,I just don't know how to write "schemeBlending" properties,would somebody please show me your "fvSchemes" files ?
or there may be something else I'm missing with  my example,tell me if you know please.
I would be very grateful if someone could help me

**Comment by ShenghaiLiao** [comment]
in file system/fvSchemes
schemeBlending
{
xBlending1
xBlending2
xBlending3
xBlending4
blendingFactor1
blendingFactor2
}
I just don't know how to set them up

**Comment by ShenghaiLiao** [comment]
as I cannot understand the properties,I have to skip it.
I try to run an example 
new problem come out

Time = 51

Courant Number mean: 0.820622 max: 0.976968
smoothSolver:  Solving for Ux, Initial residual = 0.0219358, Final residual = 6.09619e-06, No Iterations 8
smoothSolver:  Solving for Uy, Initial residual = 0.0504495, Final residual = 5.66166e-06, No Iterations 9
smoothSolver:  Solving for Uz, Initial residual = 0.0499518, Final residual = 5.75675e-06, No Iterations 9
GAMG:  Solving for p, Initial residual = 0.23412, Final residual = 0.0226034, No Iterations 1
GAMG:  Solving for p, Initial residual = 0.0684295, Final residual = 5.02282e-07, No Iterations 7
Local Flux Continuity Error:  Min -2.16393e-08	Max 1.66975e-08	RMS 7.27731e-09
Total Boundary Flux: -0.0452133
smoothSolver:  Solving for k, Initial residual = 0.00229541, Final residual = 5.99411e-06, No Iterations 4
bounding k, min: -0.00035302 max: 5.17293 average: 0.434521
#0  Foam::error::printStack(Foam::Ostream&) at ??:?
#1  Foam::sigFpe::sigHandler(int) at ??:?
#2  ? in "/lib64/libc.so.6"
#3  Foam::turbineModels::horizontalAxisWindTurbinesALM::interpolate(double, Foam::DynamicList<double, 0u, 2u, 1u>&, Foam::DynamicList<double, 0u, 2u, 1u>&) at ??:?
#4  Foam::turbineModels::horizontalAxisWindTurbinesALM::computeBladeForce() at ??:?
#5  Foam::turbineModels::horizontalAxisWindTurbinesALM::update() at ??:?
#6  ? at ??:?
#7  __libc_start_main in "/lib64/libc.so.6"
#8  ? at ??:?
Floating point exception 

so I go into pisoFoamTurbine.ALM.C
delet line "Turine.update()"
it goes on to end,but the turbine stay at the first position ,how can I make it running?

**Comment by ShenghaiLiao** [comment]
How to run pisoFoamTurbine.ALM correctly?

**Comment by DeeDiveT** [comment]
Same problem with using pisoFoamTurbine.ALM.
Is there anyone who has some ideas? thanks a lot.

**Comment by ShenghaiLiao** [comment]
@DeeDiveT 
first ,make some change on the original example in FOAM/tutorial/imcom../pisoF../LES/*,add the turbineALM model from example.ALM/constant(just copy)
then,U need to use "pisoFoam" to run for a very short time an give out a result ,finally run pisoFoamTurbine.ALM follow that result

by the way :你是清华的？

在FOAM原本的piso算例里面加几个ALM/constant的风机条件文件，先用pisoFOAM跑几秒钟，输出一个结果，再接着这个结果用psioFOAM.ALM算就行（注意0里面的初始条件和blockMeshDict的边界条件设置正确就行）

**Comment by DeeDiveT** [comment]
Hi @SH-Liao, I learned from some places that solver `pisoFoamTurbine` does not need precursor ABL data/simulation), is that right? 
Thanks for your help and recently I'm interested in performing some simulations with turbines under different (wind dir, wind speed) cases, so maybe I think `pisoFoamTurbine` is a better solution than examples in windPlantSolver.<X>.
About your question：Yes, and I'm kind of new to this field，您是在做这方面的研究吗，不知道您有没有什么建议吗，能否加个wx请教一下 androidrobots 感谢!

Best

**Comment by SH-Liao** [comment]
@DeeDiveT wechat：18351966399

**Comment by Prabs8815** [comment]
@SH-Liao & @DeeDiveT 

> as I cannot understand the properties,I have to skip it.
> I try to run an example
> new problems come out:
> 
> Courant Number mean: 0.820622 max: 0.976968
> smoothSolver: Solving for Ux, Initial residual = 0.0219358, Final residual = 6.09619e-06, No Iterations 8
> smoothSolver: Solving for Uy, Initial residual = 0.0504495, Final residual = 5.66166e-06, No Iterations 9
> smoothSolver: Solving for Uz, Initial residual = 0.0499518, Final residual = 5.75675e-06, No Iterations 9
> GAMG: Solving for p, Initial residual = 0.23412, Final residual = 0.0226034, No Iterations 1
> GAMG: Solving for p, Initial residual = 0.0684295, Final residual = 5.02282e-07, No Iterations 7
> Local Flux Continuity Error: Min -2.16393e-08 Max 1.66975e-08 RMS 7.27731e-09
> Total Boundary Flux: -0.0452133
> smoothSolver: Solving for k, Initial residual = 0.00229541, Final residual = 5.99411e-06, No Iterations 4
> bounding k, min: -0.00035302 max: 5.17293 average: 0.434521
> #0 Foam::error::printStack(Foam::Ostream&) at ??:?
> #1 Foam::sigFpe::sigHandler(int) at ??:?
> #2 ? in "/lib64/libc.so.6"
> #3 Foam::turbineModels::horizontalAxisWindTurbinesALM::interpolate(double, Foam::DynamicList<double, 0u, 2u, 1u>&, Foam::DynamicList<double, 0u, 2u, 1u>&) at ??:?
> #4 Foam::turbineModels::horizontalAxisWindTurbinesALM::computeBladeForce() at ??:?
> #5 Foam::turbineModels::horizontalAxisWindTurbinesALM::update() at ??:?
> #6 ? at ??:?
> #7 __libc_start_main in "/lib64/libc.so.6"
> #8 ? at ??:?
> Floating point exception
> 
> so I go into pisoFoamTurbine.ALM.C
> delet line "Turine.update()"
> it goes on to end,but the turbine stay at the first position ,how can I make it running?
> as there are no errors in codes, can you tell me the exactly steps how to run pisoFoamTurbine.ALM correctly?
> Any reply is very grateful.

Hi @SH-Liao  did you resolve your issue ? could you please share your experience ? I am facing a similar issue and posted a new issue here --   https://github.com/NREL/SOWFA/issues/71
