### ISSUE TITLE
Question on SOWFA installation

### ISSUE THREAD

**Issue by keinchang** [NREL/SOWFA#69]
Dear all, 
Sorry for asking some questions since I am a new user in Linux, OpenFAST,  OpenFoam and of course SOWFA. Now it seems that I have succeeded on OpenFAST and OpenFOAM. However,  I met some error message on compiling SOWFA like as follow: 

(1) missing separator error in wmake 
linux64GccDPOpt/options:66: *** missing separator.  Stop.
wmake error: file 'Make/linux64GccDPOpt/objectFiles' could not be created in /home/keinchang/SOWFA/src/turbineModels/turbineModelsOpenFAST
 
(2) Can not find -lconversion , -lsampling, -lfvOptions
/usr/bin/ld: cannot find -lconversion
/usr/bin/ld: cannot find -lsampling
/usr/bin/ld: cannot find -lfvOptions
/usr/bin/ld: cannot find -lsampling

What shall I do to solve these problems? 
Thanks you very much 

Chuan-Sheng, Chang

**Comment by SH-Liao** [comment]
see this https://github.com/pablo-benito/SOWFA-installation
