### ISSUE TITLE
pisoFoamTurbine.ADM solver

### ISSUE THREAD

**Issue by Prabs8815** [NREL/SOWFA#71]
Hello co-users of SOWFA, 

I am a newbee to SOWFA and programming in general but have worked with openFOAM and CFD in general. I am trying to put together a tutorial case for myself so that i could develop it later. As of now i did not change any base files of SOWFA but trying to change the example.ADM tutorial to an uniform inflow case  (no ABL) with pisoFoamTurbine.ADM solver. After a series of compiling and resolving "banana" type openFOAM errors i reached to the following error 

#0  Foam::error::printStack(Foam::Ostream&) at ??:?
#1  Foam::sigFpe::sigHandler(int) at ??:?
#2  ? in "/lib/x86_64-linux-gnu/libc.so.6"
#3  Foam::turbineModels::horizontalAxisWindTurbinesADM::computeBladeForce() at ??:?
#4  Foam::turbineModels::horizontalAxisWindTurbinesADM::horizontalAxisWindTurbinesADM(Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh> const&) at ??:?
#5  ? in "/home/prabhu/OpenFOAM/prabhu-2.4.0/SOWFA-2.4.0/applications/bin/linux64GccDPOpt/pisoFoamTurbine.ADM"
#6  __libc_start_main in "/lib/x86_64-linux-gnu/libc.so.6"
#7  ? in "/home/prabhu/OpenFOAM/prabhu-2.4.0/SOWFA-2.4.0/applications/bin/linux64GccDPOpt/pisoFoamTurbine.ADM"
Floating point exception (core dumped)

So in relation to the above background information and the above error description i kindly request the community to give feedback on the following questions

1.  Has anyone encountered such an error and could anyone suggest possible approaches one could apply to decode the problem ? For eg: i have checked http://openfoamwiki.net/index.php/HowTo_debugging   but reckoned that my error has  many question marks thereby rendering less info about point of error. 

2.  A more general question related to SOWFA installation and compilation: the platforms folder containing  the compiler contains only bin folder and the lib folder is instead located in the  SOWFA-2.4.0. This is not inline with the directory organisation of openFOAM-2.4.0 where both lib and bin folders are in ~/OpenFOAM/OpenFOAM-2.4.0/platforms/linux64GccDPOpt/. 
is this ok (or) does it mean that my compilation went wrong somewhere? 

Best regards and happy FOAMing

**Comment by DeeDiveT** [comment]
Hi @Prabs8815, I have encountered this error before, but I am not sure the exact solution.

If I were you, I will try the following things:

- Is the time step too large?
- Is there any turbine set out of the wind-farm field?

Hope this can help you and look forward to your feedbacks:)

**Comment by ewquon** [comment]
All, we have a recent PR #70 from @tonyinme that may offer a working example. You can check it out from here: https://github.com/tonyinme/SOWFA. Please let me know if you have any success.

**Comment by Prabs8815** [comment]
@DeeDiveT and @ewquon thanks a lot for your comments and feedback. 
For now i have a working uniform flow pisoFoamTurbine.ADM case through the link @ewquon shared. 
@DeeDiveT  I will work on understanding the turbine properties file and the implementation of the ADM/ALM models in OF through exploring the source code and some SOWFA related theses. So, for now  i am closing this issue.
