### ISSUE TITLE
Problems running example.ALM with precursor data

### ISSUE THREAD

**Issue by onepieceze** [NREL/SOWFA#78]
I want to run example.ALM with precursor data (work successfully). First, use refineHexMesh refine mesh twice:
1. toposet -dict ...
    refineHexMesh ...
2. toposet -dict ...
    refineHexMesh ...
But something went wrong on my second run of RefineHexMesh: 

Read 1261877 cells to refine from cellSet local

Reading volScalarField T
Reading volScalarField k
Reading volScalarField p_rgh
Reading volScalarField nuSgs
Reading volScalarField kappat
Reading volVectorField qwall
Reading volVectorField U
Reading volSymmTensorField Rwall

--> FOAM FATAL IO ERROR:
size 40000 is not equal to the given value of 80326

file: /home-yg/users/nsyg013_YY/OpenFOAM/run/example.ALM/12000/Rwall.boundaryField.lower from line 26 to line 34.

    From function Field<Type>::Field(const word& keyword, const dictionary&, const label)
    in file /home-yg/users/nsyg013_YY/xiezm/OpenFOAM/OpenFOAM-2.4.x/src/OpenFOAM/lnInclude/Field.C at line 292.

FOAM exiting

I check the Rwall size in precursor data, I found size of Rwall not change after first run of refineHexMesh, but U or T variables are change. So, where's the problem?

**Comment by awhitegiver** [comment]
Has anyone solved the problem？

**Comment by Didi-X** [comment]
@onepieceze @awhitegiver Has anyone solved the problem ?
