### ISSUE TITLE
How to input terrain?

### ISSUE THREAD

**Issue by xxh0523** [NREL/SOWFA#86]
Firstly, thanks for sharing this useful simulation package. 
We are using SOWFA to simulate a wind flow field that contains mountains.
Is the ABLTerrainSolver working properly?
How to input a custom terrain into SOWFA?

**Comment by rthedin** [comment]
See https://github.com/NREL/SOWFA-6/tree/dev/exampleCases/tut.ABLterrain for a simple tutorial on using terrain on SOWFA-6.

**Comment by xxh0523** [comment]
Thanks. I've got what I was looking for. This issue will be closed.

**Comment by xxh0523** [comment]
> See https://github.com/NREL/SOWFA-6/tree/dev/exampleCases/tut.ABLterrain for a simple tutorial on using terrain on SOWFA-6.

Thanks. I've got what I was looking for. This issue will be closed.

**Comment by fengbao520** [comment]
Hello, how do I run a terrain example file in sowfa-6? I am using sowfa to simulate the flow field of a wind farm with complex terrain.

**Comment by rthedin** [comment]
This github page is for SOWFA (aka SOWFA-2.4). For SOWFA-6, use [this](https://github.com/NREL/SOWFA-6) page. To your question, see my post above with a link to a complete case.
