### ISSUE TITLE
Interpolation error while calculating blade forces

### ISSUE THREAD

**Issue by hcOnel** [NREL/SOWFA#96]
Hi,
I'm getting an interpolation error while calculating the blade forces using the actuator disk model. After tinkering with almost all turbine settings, I've discovered that it happens under some specific circumstances: 

- the turbine lies within a spherical refinement region that consists of unstructured tetrahedral cells
- blade pitch is within a particular region (e.g. 8.5 - 10 degrees)

The error is gone if I change the pitch value even a bit (say, 7.5 or 11.5).
The generator and pitch control are off.
The turbine I'm using is a down-scaled version of NREL 5MW with the given data (lift and drag coefficients range from -180 to 180 deg).
I make sure that the turbine is facing toward the wind.

Your educated guess about the root of the problem would help me narrow down my search in the code.

Regards

**Comment by hcOnel** [comment]
After debugging each actuator point one by one, I've found that the problem arises from the alpha, cl, cd tabular data of an airfoil, where there are multiple entries for the same angle of attack:

https://github.com/NREL/SOWFA/blob/103832ebbae07b62220858a1e3da4b5e7d6375bd/exampleCases/example.uniform.inflow.ADM/constant/airfoilProperties/DU25_A17#L62-L63

Fixing it in the example cases might help the future users.

**Comment by ewquon** [comment]
Thanks for tracking this down, this has been corrected with https://github.com/NREL/SOWFA/commit/fb795959eb38176438e80e45378d1d80338bfa84. In the future, please feel free to submit a pull request as we generally do not have the resources to support this code.
